name: Test Docker Build
on: push
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build and run container
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: ghcr.io/${{github.repository}}:test